# 各サイトのメタ情報を保管しておく
Shop:
  # 商品仕入先サイト情報
  BuySite:
    Asos:
      SiteURL: 'https://www.asos.com/'
      ItemOfInfo:
        ItemSizeList:
          ItemSizeListCssSelector: '#main-size-select-0'

  # 商品販売先サイト情報
  SellSite:
    Buyma:
      SiteURL: 'https://www.buyma.com/'
      LoginInfo:
        URL: 'https://www.buyma.com/login/'
        ID: 'neohype808@gmail.com'
        PW: 'atms12345b'
        IdCssSelector: '#txtLoginId'
        PwCssSelector: '#txtLoginPass'
        LoginButtonCssSelector: '#login_do'
      ItemOfInfo:
        ItemListInfo:
          ItemListURL: 'https://www.buyma.com/my/sell/#/'
          ItemNameCssSelector: '#inputform > table > tbody > tr > td.item_name > p > a'
          ItemIdCssSelector: '#inputform > table > tbody > tr > td.item_name > p.fab-typo-xsmall.mg_t5 > a'
        ItemStockInfo:
          ItemStockInfoCssSelector:
            # buymaの出品リストから在庫状況にたどり着くまでにクリックする必要のあるリンクと入力の必要な箇所のCSSセレクターを記述する
            # 在庫ウィジット表示編集リンク
            - '#inputform > table > tbody > tr > td.js_item_colorsize_edit > a'
            # 在庫ウィジットのサイズごとの在庫状況
            - '#my > div.ui-dialog.ui-widget.ui-widget-content.ui-corner-all.fab-dialog--primary.cs-dialog > div.js-color-size-popup-box.fab-design-mg--t15.ui-dialog-content.ui-widget-content > div > div.js-size-input-wrap.color-size-color-wrap > table > tbody > tr > td.fab-design-txtleft.fab-form > div > select'
            # 在庫ウィジットの買い付けできる合計数量
            - '#my > div.ui-dialog.ui-widget.ui-widget-content.ui-corner-all.fab-dialog--primary.cs-dialog > div.js-color-size-popup-box.fab-design-mg--t15.ui-dialog-content.ui-widget-content > div > div.sell-unit-summary-wrap > div > div > span > input.js-colorsize-capacity-amount.sell-unit-summary-input'
            # 在庫ウェジットの更新ボタン
            - '#my > div.ui-dialog.ui-widget.ui-widget-content.ui-corner-all.fab-dialog--primary.cs-dialog > div.js-color-size-popup-box.fab-design-mg--t15.ui-dialog-content.ui-widget-content > div > div.csp-decide > a.js-commit-changes.fab-button.fab-button--primary.fab-button--m'
